config/routes.rb
Rails.application.routes.draw do
  resources :order_items
  resources :orders
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end


  namespace :admin do
    resources :restaurants
    resources :menus
    resources :allergens
    resources :sub_menus
    resources :menu_items
    resources :orders
    controller :menu_items do
      get 'set_item_status' => :set_item_status
      get 'set_item_empty_status' => :set_item_empty_status
    end
    controller :allergens do
      get 'allergen_slett' => :destroy
    end
    controller :menus do
      get 'set_menu_status' => :set_menu_status
    end
    controller :sub_menus do
      get 'set_sub_menu_status' => :set_sub_menu_status
    end
  end

  # Bruker
  resources :menu
  resources :restaurant
  resources :menu_item
  controller :orders do
    post 'make_order' => :make_order
    post 'add_to_cart' => :addToCart
    post 'add_one_to_cart' => :addOneToCart
    delete 'remove_one_from_cart' => :removeOneFromCart
    delete 'remove_all_from_cart' => :removeAllFromCart
    delete 'empty_cart' => :emptyCart
    get 'total_price' => :total_price
  end
  get "/selected_menu" => 'menu#selected_menu', as: 'selected_menu'


  namespace :api do
    namespace :v1 do
      controller :api do
        #get 'create_order' => :create_order

        get 'total_price' => :total_price
        get 'total_amount' => :total_amount
        get 'add_to_cart' => :add_to_cart
        get 'add_one_to_cart' => :add_one_to_cart
        get 'remove_one_from_cart' => :remove_one_from_cart
        get 'remove_all_from_cart' => :remove_all_from_cart
        get 'empty_cart' => :empty_cart

        get 'get_orders' => :get_orders
        get 'get_order_items' => :get_order_items
        get 'set_order_finish' => :set_order_finish
        get 'set_order_paid' => :set_order_paid
        get 'change_order_item_status' => :change_order_item_status

        get 'set_item_status' => :set_item_status

      end
    end
  end

  # Admin
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/sub_menu.rb
class SubMenu < ApplicationRecord
  has_many :menu_items
  belongs_to :menu

=begin
  enum status: {
    "remove" => 0,
    "hide" => 1,
    "visible" => 2
  }
=end

end

app/controllers/admin/sub_menus_controller.rb
class Admin::SubMenusController < ApplicationController
  before_action :set_sub_menu, only: %i[ show edit update ]

  # GET /sub_menus/new
  def new
    p "hei"
    @menu_id=params['menu_id']
    p @menu_id
    @sub_menu = SubMenu.new(:menu_id=>@menu_id)
    p @sub_menu
    @restaurant = Restaurant.find(session[:restaurant_id])
    verify_signin(@restaurant.id)
  end

  # GET /sub_menus/1/edit
  def edit
    @restaurant = Restaurant.find(session[:restaurant_id])
    verify_signin(@restaurant.id)
  end

  # POST /sub_menus or /sub_menus.json
  def create
    p "hå"
    @sub_menu = SubMenu.new(sub_menu_params)
    p @sub_menu

    verify_signin(@sub_menu.menu.restaurant.id)

    respond_to do |format|
      if @sub_menu.save
        format.html { redirect_to admin_restaurant_url(@sub_menu.menu.restaurant.id), notice: "Sub menu was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sub_menus/1 or /sub_menus/1.json
  def update
    @restaurant = Restaurant.find(session[:restaurant_id])
    verify_signin(@restaurant.id)
    respond_to do |format|
      if @sub_menu.update(sub_menu_params)
        format.html { redirect_to admin_restaurant_url(@sub_menu.menu.restaurant.id), notice: "Sub menu was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sub_menus/1 or /sub_menus/1.json
  def destroy
    @restaurant = Restaurant.find(session[:restaurant_id])
    verify_signin(@restaurant.id)
    sub_menu=SubMenu.find(params[:a_id])
    sub_menu.destroy
    respond_to do |format|
      format.html { redirect_to admin_restaurant_url(@sub_menu.menu.restaurant.id), notice: "Sub menu was successfully destroyed." }

    end
  end

  def set_sub_menu_status
    p "sub_menu Status"
    sub_menu = SubMenu.find(params[:sub_menu_id])
    sub_menu.status = params[:status]
    p "sub_menu Status2"
    sub_menu.save!
    p "sub_menu Status3"
    respond_to do |format|
      format.html { redirect_to admin_restaurant_url(sub_menu.menu.restaurant.id), notice: "Sub menu was successfully changed." }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_sub_menu
    @sub_menu = SubMenu.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def sub_menu_params
    params.require(:sub_menu).permit(:name, :status, :number, :menu_id)
  end
end

app/views/admin/sub_menus/_form_base.html.erb
<% if sub_menu.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(sub_menu.errors.count, "error") %> prohibited this sub menu from being saved:</h2>

    <ul>
      <% sub_menu.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div>
  <div class="flex flex-col rounded-2xl lg:w-1/3">


    <div class="mx-10">

      <div class="field text-gray-700 pt-5">
        <% form.label :menu_id, class: 'text-gray-700'  %>
        <%= form.text_field :menu_id, class: 'w-80 border-gray-800 rounded-lg'  %>
      </div>
      <div class="field text-gray-700 pt-5">
        <%= form.label "Navn", class: 'text-gray-700' %><br>
        <%= form.text_field :name, class: 'w-80 border-gray-800 rounded-lg' %>
      </div>
      <div class="field text-gray-700 pt-5">
        <%= form.label "Rekkefølge", class: 'text-gray-700' %><br>
        <%= form.text_field :number, class: 'w-80 border-gray-800 rounded-lg' %>
      </div>

      <div class="actions text-gray-700 pt-5">
        <%= form.submit "Lagre", class: 'btn-indigo' %>
      </div>
    </div>
  </div>
</div>

app/views/admin/sub_menus/_form_edit.html.erb
<%= form_with(model: sub_menu, url: admin_sub_menu_url, local: true) do |form| %>

  <%= render 'form_base', sub_menu: sub_menu, form: form %>
<% end %>

app/views/admin/sub_menus/_form_new.html.erb
<%= form_with(model: sub_menu, url: admin_sub_menus_url, local: true) do |form| %>
  <%= render 'form_base', sub_menu: sub_menu, form: form %>
<% end %>

app/views/admin/sub_menus/edit.html.erb
<%= link_to '<', admin_restaurant_path(@restaurant), class: "pr-5" %>
<div class="flex justify-center">

  <div>
    <h1 class="text-4xl m-4">Edit Sub Menu</h1>

    <%= render 'form_edit', sub_menu: @sub_menu %>
  </div>
</div>

app/views/admin/sub_menus/new.html.erb
<%= link_to '<', admin_restaurant_path(@restaurant), class: "pr-5" %>
<div class="flex justify-center">

  <div>
    <h1 class="text-4xl m-4">New Sub Menu</h1>
    <%= render 'form_new', sub_menu: @sub_menu %>
  </div>
</div>