config/routes.rb
Rails.application.routes.draw do
  resources :order_items
  resources :orders
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end


  namespace :admin do
    resources :restaurants
    resources :menus
    resources :allergens
    resources :sub_menus
    resources :menu_items
    resources :orders
    controller :menu_items do
      get 'set_item_status' => :set_item_status
      get 'set_item_empty_status' => :set_item_empty_status
    end
    controller :allergens do
      get 'allergen_slett' => :destroy
    end
    controller :menus do
      get 'set_menu_status' => :set_menu_status
    end
    controller :sub_menus do
      get 'set_sub_menu_status' => :set_sub_menu_status
    end
  end

  # Bruker
  resources :menu
  resources :restaurant
  resources :menu_item
  controller :orders do
    post 'make_order' => :make_order
    post 'add_to_cart' => :addToCart
    post 'add_one_to_cart' => :addOneToCart
    delete 'remove_one_from_cart' => :removeOneFromCart
    delete 'remove_all_from_cart' => :removeAllFromCart
    delete 'empty_cart' => :emptyCart
    get 'total_price' => :total_price
  end
  get "/selected_menu" => 'menu#selected_menu', as: 'selected_menu'


  namespace :api do
    namespace :v1 do
      controller :api do
        #get 'create_order' => :create_order

        get 'total_price' => :total_price
        get 'total_amount' => :total_amount
        get 'add_to_cart' => :add_to_cart
        get 'add_one_to_cart' => :add_one_to_cart
        get 'remove_one_from_cart' => :remove_one_from_cart
        get 'remove_all_from_cart' => :remove_all_from_cart
        get 'empty_cart' => :empty_cart

        get 'get_orders' => :get_orders
        get 'get_order_items' => :get_order_items
        get 'set_order_finish' => :set_order_finish
        get 'set_order_paid' => :set_order_paid
        get 'change_order_item_status' => :change_order_item_status

        get 'set_item_status' => :set_item_status

      end
    end
  end

  # Admin
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/menu_item.rb
class MenuItem < ApplicationRecord
  has_many :order_items
  has_many :allergen_items
  belongs_to :menu
  has_one :sub_menu
  has_one_attached :image

=begin
  enum statuss: {
    remove: 0,
    hide: 1,
    visible: 2
  }
  enum empty: {
    has_ingredients: 0,
    limited: 1,
    empty: 2
  }
=end

  def get_allergen_names_short
    allergens_arr = Array.new
    allergen_items.each do |allergen|
      allergens_arr << allergen.allergen.short_name
    end
    allergens_arr
  end

  def get_allergen_names_long
    allergens_arr = Array.new
    allergen_items.each do |allergen|
      allergens_arr << allergen.allergen.name
    end
    allergens_arr
  end

  private

  def ensure_not_referenced_by_any_line_item
    return if order_items.present?

    errors.add(:base, 'Order item pressent')
    throw :abort
  end
end

app/controllers/admin/menu_items_controller.rb
class Admin::MenuItemsController < ApplicationController
  before_action :set_menu_item, only: %i[ show edit update destroy ]


  # GET /menu_items/new
  def new
    @menu_id=params['menu_id']
    @menu_item = MenuItem.new(:menu_id=>@menu_id)

    @restaurant = Restaurant.find(session[:restaurant_id])
    verify_signin(@restaurant.id)
  end

  # GET /menu_items/1/edit
  def edit
    @restaurant = @menu_item.menu.restaurant
    verify_signin(@restaurant.id)
  end

  # POST /menu_items or /menu_items.json
  def create
    @menu_item = MenuItem.new(menu_item_params)

    verify_signin(@menu_item.menu.restaurant.id)

    respond_to do |format|
      if @menu_item.save
        format.html { redirect_to  admin_restaurant_url(@menu_item.menu.restaurant.id), notice: "Menu item was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /menu_items/1 or /menu_items/1.json
  def update
    respond_to do |format|
      if @menu_item.update(menu_item_params)
        format.html { redirect_to admin_restaurant_url(@menu_item.menu.restaurant.id), notice: "Menu item was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menu_items/1 or /menu_items/1.json
  def destroy
    @menu_item.status=3
    respond_to do |format|
      format.html { redirect_to admin_restaurant_url(@menu_item.menu.restaurant.id), notice: "Menu item was successfully destroyed." }

    end
  end

  def set_item_status
    p "menu_items Status"
    item = MenuItem.find(params[:item_id])
    item.status = params[:status]
    p "menu_items Status2"
    item.save!
    p "menu_items Status3"
    respond_to do |format|
      format.html { redirect_to admin_restaurant_url(item.menu.restaurant.id), notice: "Menu item was successfully changed." }
    end

  end

  def set_item_empty_status
    p "menu_items Status"
    item = MenuItem.find(params[:item_id])
    item.empty = params[:status]
    p params[:status]
    p item.status
    p "menu_items Status2"
    item.save!
    p "menu_items Status3"
    respond_to do |format|
      format.html { redirect_to admin_restaurant_url(item.menu.restaurant.id), notice: "Menu item was successfully changed." }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_menu_item
      @menu_item = MenuItem.find(params[:id])
    end
    # Only allow a list of trusted parameters through.
    def menu_item_params
      used_allergens = params[:allergens]

      params_to_return = params.require(:menu_item).permit(:name, :number, :description, :price, :menu_id, :image, :sub_menu_id)

      AllergenItem.where(:menu_item_id=>params[:id]).each do |item|
        item.destroy
      end

      allergens_to_add = []
      if used_allergens != nil 
        used_allergens.each do |allergen_param|
          p "Allergen: #{allergen_param[0]}"
          allergen_item = AllergenItem.new(:menu_item_id=>params[:id], :allergen_id=>allergen_param[0])
          allergens_to_add << allergen_item
        end
        params_to_return[:allergen_items] = allergens_to_add
      end



      p "Params to return #{params_to_return}"

      params_to_return
    end
end

app/controllers/menu_item_controller.rb
class MenuItemController < ApplicationController
  def show
    @menu_item = MenuItem.find(params[:id])
    @restaurant = @menu_item.menu.restaurant
  end
end

app/controllers/menu_items_controller.rb
class MenuItemsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_menu_item, only: %i[ show edit update destroy ]

  # GET /menu_items or /menu_items.json
  def index
    @menu_items = MenuItem.all
  end

  # GET /menu_items/1 or /menu_items/1.json
  def show
  end

  # GET /menu_items/new
  def new
    @menu_item = MenuItem.new
  end

  # GET /menu_items/1/edit
  def edit
  end

  # POST /menu_items or /menu_items.json
  def create
    @menu_item = MenuItem.new(menu_item_params)

    respond_to do |format|
      if @menu_item.save
        format.html { redirect_to @menu_item, notice: "Menu item was successfully created." }
        format.json { render :show, status: :created, location: @menu_item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @menu_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /menu_items/1 or /menu_items/1.json
  def update
    respond_to do |format|
      if @menu_item.update(menu_item_params)
        format.html { redirect_to @menu_item, notice: "Menu item was successfully updated." }
        format.json { render :show, status: :ok, location: @menu_item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @menu_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menu_items/1 or /menu_items/1.json
  def destroy
    @menu_item.destroy
    respond_to do |format|
      format.html { redirect_to menu_items_url, notice: "Menu item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_menu_item
      @menu_item = MenuItem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def menu_item_params
      params.require(:menu_item).permit(:name, :image_url, :description, :price, :menu_id)
    end
end

app/helpers/menu_items_helper.rb
module MenuItemsHelper
end

app/views/menu_items/_form.html.erb
<%= form_with(model: menu_item, local: true) do |form| %>
  <% if menu_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(menu_item.errors.count, "error") %> prohibited this menu_item from being saved:</h2>

      <ul>
        <% menu_item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :menu_id %>
    <%= form.text_field :menu_id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/menu_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Menu Items</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Image url</th>
      <th>Description</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @menu_items.each do |menu_item| %>
      <tr>
        <td><%= menu_item.name %></td>
        <td><%= menu_item.image_url %></td>
        <td><%= menu_item.description %></td>
        <td><%= menu_item.price %></td>
        <td><%= link_to 'Show', menu_item %></td>
        <td><%= link_to 'Edit', edit_menu_item_path(menu_item) %></td>
        <td><%= link_to 'Destroy', menu_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Menu Item', new_menu_item_path %>

app/views/menu_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @menu_item.name %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @menu_item.image_url %>
</p>

<p>
  <strong>Description:</strong>
  <%= @menu_item.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @menu_item.price %>
</p>

<%= link_to 'Edit', edit_menu_item_path(@menu_item) %> |
<%= link_to 'Back', menu_items_path %>