config/routes.rb
Rails.application.routes.draw do
  resources :order_items
  resources :orders
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end


  namespace :admin do
    resources :restaurants
    resources :menus
    resources :allergens
    resources :sub_menus
    resources :menu_items
    resources :orders
    controller :menu_items do
      get 'set_item_status' => :set_item_status
      get 'set_item_empty_status' => :set_item_empty_status
    end
    controller :allergens do
      get 'allergen_slett' => :destroy
    end
    controller :menus do
      get 'set_menu_status' => :set_menu_status
    end
    controller :sub_menus do
      get 'set_sub_menu_status' => :set_sub_menu_status
    end
  end

  # Bruker
  resources :menu
  resources :restaurant
  resources :menu_item
  controller :orders do
    post 'make_order' => :make_order
    post 'add_to_cart' => :addToCart
    post 'add_one_to_cart' => :addOneToCart
    delete 'remove_one_from_cart' => :removeOneFromCart
    delete 'remove_all_from_cart' => :removeAllFromCart
    delete 'empty_cart' => :emptyCart
    get 'total_price' => :total_price
  end
  get "/selected_menu" => 'menu#selected_menu', as: 'selected_menu'


  namespace :api do
    namespace :v1 do
      controller :api do
        #get 'create_order' => :create_order

        get 'total_price' => :total_price
        get 'total_amount' => :total_amount
        get 'add_to_cart' => :add_to_cart
        get 'add_one_to_cart' => :add_one_to_cart
        get 'remove_one_from_cart' => :remove_one_from_cart
        get 'remove_all_from_cart' => :remove_all_from_cart
        get 'empty_cart' => :empty_cart

        get 'get_orders' => :get_orders
        get 'get_order_items' => :get_order_items
        get 'set_order_finish' => :set_order_finish
        get 'set_order_paid' => :set_order_paid
        get 'change_order_item_status' => :change_order_item_status

        get 'set_item_status' => :set_item_status

      end
    end
  end

  # Admin
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/allergen.rb
class Allergen < ApplicationRecord
  has_many :allergen_item, dependent: :destroy
  belongs_to :restaurant
end

app/models/allergen_item.rb
class AllergenItem < ApplicationRecord
  belongs_to :allergen
  belongs_to :menu_item
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/menu.rb
class Menu < ApplicationRecord
    has_many :menu_items, dependent: :destroy
    has_many :sub_menus, dependent: :destroy
    belongs_to :restaurant
    has_one_attached :image

=begin
    enum status: {
      "remove" => 0,
      "hide" => 1,
      "visible" => 2
    }
=end

    scope :visible, -> { where(status: 2) }
    scope :ordered, -> { order(:number) }

end

app/models/menu_item.rb
class MenuItem < ApplicationRecord
  has_many :order_items
  has_many :allergen_items
  belongs_to :menu
  has_one :sub_menu
  has_one_attached :image

=begin
  enum statuss: {
    remove: 0,
    hide: 1,
    visible: 2
  }
  enum empty: {
    has_ingredients: 0,
    limited: 1,
    empty: 2
  }
=end

  def get_allergen_names_short
    allergens_arr = Array.new
    allergen_items.each do |allergen|
      allergens_arr << allergen.allergen.short_name
    end
    allergens_arr
  end

  def get_allergen_names_long
    allergens_arr = Array.new
    allergen_items.each do |allergen|
      allergens_arr << allergen.allergen.name
    end
    allergens_arr
  end

  private

  def ensure_not_referenced_by_any_line_item
    return if order_items.present?

    errors.add(:base, 'Order item pressent')
    throw :abort
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items, dependent: :destroy
  belongs_to :restaurant

  enum order_status: {
    "Started" => 0,
    "Finished" => 1,
    "Paid" => 2
  }

  def add_menu_item(item_id:, quantity:, order_item_status:)
    p "test add_menu_item"
    current_item = order_items.build(menu_item_id: item_id, quantity: quantity, order_item_status: order_item_status)
    current_item.save!
    p current_item

    current_item
  end

  def total_price
    order_items.to_a.sum{|item|item.total_price}
  end

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :menu_item
  belongs_to :order

  enum order_item_status: {
    "Started" => 0,
    "Finished" => 1
  }

  def price
    menu_item.price
  end

  def total_price
    menu_item.price * quantity
  end

end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :menus, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :allergens, dependent: :destroy
  validates :username, presence: true, uniqueness: true
  has_secure_password

  def get_allergen_map
    allergens.map { |a| a.short_name + ' = ' + a.name }
  end

  def visible_menus
    menus.visible.ordered
  end
end

app/models/sub_menu.rb
class SubMenu < ApplicationRecord
  has_many :menu_items
  belongs_to :menu

=begin
  enum status: {
    "remove" => 0,
    "hide" => 1,
    "visible" => 2
  }
=end

end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
  def show
    @menu = Menu.find(params[:id])
    @restaurant = @menu.restaurant
  end

  def selected_menu
    @selected = Menu.find(params[:menu_id])
    respond_to do |format|
      format.js { render layout: false, content_type: 'text/javascript' }
    end
  end
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_active_class(name, active_class_names, options = {}, html_options = {}, &block)
    html_options[:class] = html_options[:class].to_s + active_class_names if current_page?(options.to_s)
    link_to name, options, html_options, &block
  end


  def is_selected?(page_name)
    if params[:action] == page_name
      "selected"
    end
  end
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/menu_items_helper.rb
module MenuItemsHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/restaurant_helper.rb
module RestaurantHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rubynor Qr Meny System</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_pack_tag "application", "data-turbo-track": "reload" %>
  <%= stylesheet_link_tag "tailwind" %>
  <%= stylesheet_link_tag "inter-font" %>
</head>

<body class="relative lg:bg-gray-100 font-sans">
  <div class="pb-14">
    <% if @restaurant %>
      <%= render 'shared/header' %>
    <% end %>
  </div>
  <div class="">
    <%= yield %>
  </div>

  <div class="flex justify-center">
    <div class="fixed top-16">
      <% if @restaurant %>
        <%= react_component("modal/modalAlertCart", { restaurantId: @restaurant.id }) %>
      <% end %>
    </div>
    <div class="fixed top-12">
      <% if @restaurant %>
        <%= react_component("modal/modalOrdered", { restaurantId: @restaurant.id }) %>
      <% end %>
    </div>
    <div class="fixed top-12">
      <%= react_component("modal/modalMenu") %>
      <%= react_component("modal/modalMenuItem") %>
      <%= react_component("modal/modalAllergen") %>
    </div>
  </div>
</body>
</html>

app/views/shared/_header.html.erb
<nav class="flex items-center justify-between flex-wrap bg-white lg:bg-gray-800 p-2 fixed w-full z-10 pin-t border-b border-gray-200 z-50">

  <div class="flex items-center flex-no-shrink text-gray-900 lg:text-gray-100 mr-6">
    <%= link_to @restaurant.name, restaurant_path(:id => @restaurant.id), class: "text-md lg:text-2xl pl-2 font-semibold uppercase text-gray-900 lg:text-white hover:text-gray-600 lg:hover:text-gray-200 no-underline hover:text-white hover:no-underline" %>
  </div>
  <div class="mr-3">
    <%= link_to order_path(:id => @restaurant.id) do %>
      <%= react_component("cart_icon/cart_icon") %>
    <% end %>
  </div>

  <% if session[:restaurant_id] != nil %>
    <div class="block lg:hidden">
      <button id="nav-toggle" class="flex items-center px-3 py-2 border rounded text-gray-600 hover:text-gray-600">
        <svg class="fill-current h-5 w-5" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
          <path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/>
        </svg>
      </button>
    </div>
  <% end %>

  <div class="w-full flex-grow lg:flex lg:items-center lg:w-auto hidden lg:block pt-6 lg:pt-0" id="nav-content">
    <ul class="list-reset lg:flex justify-end flex-1 items-center">
      <% if session[:restaurant_id] != nil %>
        <li class="mr-3">
          <%= link_to 'Meny', restaurant_path(:id => @restaurant.id), class: 'nav-btn' %>
        </li>
        <li class="mr-3 hidden lg:block text-gray-200">|</li>
        <li class="mr-3 block lg:hidden">
          <hr style="height:2px;border-width:0;color:gray;background-color:#808080"/>
        </li>
        <li class="mr-3">
          <%= link_to 'Admin', admin_restaurant_path(:id => @restaurant.id), class: "nav-btn" %>
        </li>
        <li class="mr-3">
          <%= link_to 'Ordre', admin_order_path(:id => @restaurant.id), class: "nav-btn" %>
        </li>
        <li class="mr-3">
          <%= link_to 'Logg ut', logout_path, method: :delete, class: "nav-btn" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

<script>
    document.getElementById('nav-toggle').onclick = function () {
        document.getElementById("nav-content").classList.toggle("hidden");
    }
</script>