config/routes.rb
Rails.application.routes.draw do
  resources :order_items
  resources :orders
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end


  namespace :admin do
    resources :restaurants
    resources :menus
    resources :allergens
    resources :sub_menus
    resources :menu_items
    resources :orders
    controller :menu_items do
      get 'set_item_status' => :set_item_status
      get 'set_item_empty_status' => :set_item_empty_status
    end
    controller :allergens do
      get 'allergen_slett' => :destroy
    end
    controller :menus do
      get 'set_menu_status' => :set_menu_status
    end
    controller :sub_menus do
      get 'set_sub_menu_status' => :set_sub_menu_status
    end
  end

  # Bruker
  resources :menu
  resources :restaurant
  resources :menu_item
  controller :orders do
    post 'make_order' => :make_order
    post 'add_to_cart' => :addToCart
    post 'add_one_to_cart' => :addOneToCart
    delete 'remove_one_from_cart' => :removeOneFromCart
    delete 'remove_all_from_cart' => :removeAllFromCart
    delete 'empty_cart' => :emptyCart
    get 'total_price' => :total_price
  end
  get "/selected_menu" => 'menu#selected_menu', as: 'selected_menu'


  namespace :api do
    namespace :v1 do
      controller :api do
        #get 'create_order' => :create_order

        get 'total_price' => :total_price
        get 'total_amount' => :total_amount
        get 'add_to_cart' => :add_to_cart
        get 'add_one_to_cart' => :add_one_to_cart
        get 'remove_one_from_cart' => :remove_one_from_cart
        get 'remove_all_from_cart' => :remove_all_from_cart
        get 'empty_cart' => :empty_cart

        get 'get_orders' => :get_orders
        get 'get_order_items' => :get_order_items
        get 'set_order_finish' => :set_order_finish
        get 'set_order_paid' => :set_order_paid
        get 'change_order_item_status' => :change_order_item_status

        get 'set_item_status' => :set_item_status

      end
    end
  end

  # Admin
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :menus, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :allergens, dependent: :destroy
  validates :username, presence: true, uniqueness: true
  has_secure_password

  def get_allergen_map
    allergens.map { |a| a.short_name + ' = ' + a.name }
  end

  def visible_menus
    menus.visible.ordered
  end
end

app/controllers/admin/restaurants_controller.rb
class Admin::RestaurantsController < ApplicationController
  before_action :set_restaurant, only: %i[ show edit update destroy ]

  # GET /restaurants or /restaurants.json
  def index
    # Send the user directly to their own restaurant
    redirect_to admin_restaurant_url id: session[:restaurant_id]
    verify_signin(@restaurant.id)
  end

  # GET /restaurants/1 or /restaurants/1.json
  def show
    verify_signin(@restaurant.id)

    @allergens = @restaurant.allergens
    @all_menus = @restaurant.menus
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants or /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)
    verify_signin(@restaurant.id)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to admin_restaurants_url, notice: "Restaurant was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1 or /restaurants/1.json
  def update
    verify_signin(@restaurant.id)
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to admin_restaurant_url(@restaurant.id), notice: "Restaurant was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1 or /restaurants/1.json
  def destroy
    verify_signin(@restaurant.id)
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to admin_restaurants_url, notice: "Restaurant was successfully destroyed." }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :username, :password, :password_confirmation)
    end
end

app/controllers/restaurant_controller.rb
class RestaurantController < ApplicationController
  def show
    if params[:location] != nil && params[:location] != 0
      session[:location] = params[:location]
      session[:cart]=[]
    end

    @restaurant = Restaurant.find(params[:id])
    @menus = @restaurant.visible_menus
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: %i[ show edit update destroy ]

  # GET /restaurants or /restaurants.json
  def index
    @restaurants = Restaurant.all
  end

  # GET /restaurants/1 or /restaurants/1.json
  def show
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants or /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: "Restaurant was successfully created." }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1 or /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: "Restaurant was successfully updated." }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1 or /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: "Restaurant was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :username, :password, :password_confirmation)
    end
end

app/helpers/restaurant_helper.rb
module RestaurantHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/admin/restaurants/_form.base.html.erb
<% if restaurant.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

    <ul>
      <% restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="field">
  <%= form.label :name %>
  <%= form.text_field :name %>
</div>

<div class="field">
  <%= form.label :username %>
  <%= form.text_field :username %>
</div>

<div class="field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

<div class="field">
  <%= form.label :password_confirmation %>
  <%= form.password_field :password_confirmation %>
</div>

<div class="actions">
  <%= form.submit %>
</div>

app/views/admin/restaurants/_form_base.html.erb
<div class="m-4 space-y-8">
<% if restaurant.errors.any? %>
  <div class="w-80 p-5 border-2 border-red-600 text-red-600">>
    <h2><%= pluralize(restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

    <ul>
      <% restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div >
  <%= form.label "Navn", class: 'text-gray-700' %>
  <div>
  <%= form.text_field :name, class: 'w-80 border-gray-800 rounded-lg' %></div>
</div>

<div class="field">
  <%= form.label "Brukernavn", class: 'text-gray-700' %>
  <div>
  <%= form.text_field :username, class: 'w-80 border-gray-800 rounded-lg'  %>
  </div>
</div>

<div class="field">
  <%= form.label "Nytt passord", class: 'text-gray-700' %>
  <div>
    <%= form.password_field :password, class: 'w-80 border-gray-800 rounded-lg'  %>
  </div>
</div>

<div class="field">
  <%= form.label "Repeter passord", class: 'text-gray-700' %>
  <div>
    <%= form.password_field :password_confirmation, class: 'w-80 border-gray-800 rounded-lg'  %>
  </div>
</div>

<div class="actions">
  <%= form.submit "Lagre endring", class: 'btn-indigo'  %>
</div>
</div>

app/views/admin/restaurants/_form_edit.html.erb
<%= form_with(model: restaurant, url: admin_restaurant_url, local: true) do |form| %>
  <%= render 'form_base', restaurant: restaurant, form: form %>
<% end %>

app/views/admin/restaurants/_form_new.erb
<%= form_with(model: restaurant, url: admin_restaurants_url, local: true) do |form| %>
  <%= render 'form_base', restaurant: restaurant, form: form %>
<% end %>

app/views/admin/restaurants/edit.html.erb
<%= link_to '<', admin_restaurant_path(@restaurant), class: "pr-5"  %>
<div class="flex justify-center">
  <div>
    <h1 class="text-4xl m-4">Editing Restaurant</h1>
    <br>
    <%= render 'form_edit', restaurant: @restaurant %>
  </div>
</div>

app/views/admin/restaurants/show.html.erb
<div class="container mx-auto px-4 lg:px-10 pb-1 pt-4">
  <div>
    <div class="pt-5">
      <strong>QR Kode</strong>
      <div class="flex pb-5">
        <%= react_component("admin_qr/admin_qr", {restaurant_id: @restaurant.id}) %>
        <div class="pl-5">
          <div>
            <strong>Navn:</strong>
            <%= @restaurant.name %>
          </div>

          <div>
            <strong>Brukernavn:</strong>
            <%= @restaurant.username %>
          </div>
          <div class="mt-2">
            <%= link_to 'Rediger', edit_admin_restaurant_path(@restaurant), class: "text-sm bg-gray-200 border border-gray-400 rounded hover:bg-gray-300 py-1 px-2" %>
          </div>
        </div>
      </div>
    </div>


    <div class="container mx-auto bg-gray-700 px-4 pb-1 pt-4 ">
      <div class="font-bold text-white text-3xl my-5">
        Menyer
      </div>
      <% @restaurant.menus.where.not(:status => 0).order('number, id').each do |menu| %>
        <% menu_items = menu.menu_items.order('length(number), number, id') %>
        <% sub_menus = menu.sub_menus.order('length(number), number, id') %>
        <%= react_component("admin_menu/menu_item", { menu: menu, menuItems: menu_items, sub_menus: sub_menus }) %>
      <% end %>
      <div class="h-20 mt-10">
        <%= link_to 'Ny meny', new_admin_menu_path(:restaurant_id => params[:id]), id: "new_menu", class: "text-sm bg-gray-200 border border-gray-400 rounded hover:bg-gray-300 py-1 px-2" %>
      </div>

      <% @all_menus.where.not(:status => 0).each do |one_menu| %>
        <% sub_menus = one_menu.sub_menus%>
        <% sub_menus.where.not(:status => 0).order('length(number), number, id').each do |sub_menu| %>
          <%= sub_menu.name %>
        <% end %>
      <% end %>

      <div class="h-20 mt-10">
        <% link_to 'Ny under meny', new_admin_sub_menu_path(:restaurant_id => params[:id]), class: "text-sm bg-gray-200 border border-gray-400 rounded hover:bg-gray-300 py-1 px-2" %>
      </div>
    </div>
    <div class="container mx-auto bg-gray-700 px-4 pb-1 pt-4 ">
      <div class="font-bold text-white text-3xl my-5">
        Allergener
      </div>
      <% @allergens.each do |allergen| %>
        <%= react_component("admin_menu/allergen_item", { allergen: allergen }) %>
      <% end %>
      <div class="h-20 mt-10">
        <%= link_to 'Nytt allergen', new_admin_allergen_path, class: "text-sm bg-gray-200 border border-gray-400 rounded hover:bg-gray-300 py-1 px-2" %>
      </div>
    </div>
  </div>
</div>